"""Generate the minimal Deno-safe identity projection from Source Registry V2."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scrapers"))
from source_registry_v2 import registry_snapshot

snapshot = registry_snapshot()
rows = [{"canonical_source": item["canonical_source"], "emitted_aliases": item["emitted_aliases"]} for item in snapshot["sources"]]
target = ROOT / "supabase/functions/_shared/generated-source-registry.ts"
target.write_text("// Generated by scripts/generate_edge_source_registry.py. Do not edit manually.\n"
                  f"export const EDGE_SOURCE_REGISTRY_HASH = {snapshot['registry_hash']!r}\n"
                  f"export const EDGE_SOURCE_IDENTITIES = {rows!r} as const\n", encoding="utf-8")
print(target)
