from pathlib import Path
import subprocess, sys
root = Path(__file__).resolve().parents[1]
subprocess.run([sys.executable, str(root / 'scripts/generate_edge_source_registry.py')], check=True, stdout=subprocess.DEVNULL)
text = (root / 'supabase/functions/_shared/generated-source-registry.ts').read_text(encoding='utf-8')
assert "'canonical_source': 'oya'" in text and "'oyaop'" in text
assert "Generated by scripts/generate_edge_source_registry.py" in text
print('verify_edge_source_registry: PASS')
