import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (p: string) => readFileSync(new URL(p, import.meta.url), 'utf8')
const migration = read('../supabase/migrations/202610020001_opportunity_pipeline_ledger.sql')
const correctiveMigration = read('../supabase/migrations/202610030001_pipeline_trace_contract_v2.sql')
const verifySql = read('../artifacts/opportunity-pipeline/verify-prod.sql')
const sink = read('../scrapers/opportunity_sink.py')
const runner = read('./run_scraper_monitored.py')
const registryCore = read('../scrapers/source_registry_v2.py')
const admin = read('../netlify/functions/admin-data.ts')
const adminView = read('../src/components/admin/SourceOperationsView.tsx')

assert.match(migration, /create table if not exists public\.opportunity_ingestion_events/i)
assert.match(migration, /create or replace view public\.opportunity_pipeline_status/i)
assert.match(migration, /from public\.opportunities o\s+left join latest_ingestion/i)
assert.match(migration, /left join latest_observation lo/i)
assert.match(migration, /left join public\.opportunity_factory_snapshots fs/i)
assert.match(migration, /left join public\.opportunity_universe_state u/i)
assert.match(migration, /grant select on public\.opportunity_pipeline_status to service_role/i)
assert.match(migration, /create or replace function public\.admin_opportunity_pipeline_ledger/i)
assert.match(correctiveMigration, /add column if not exists trace_contract_version/i)
assert.match(correctiveMigration, /check \([\s\S]*trace_contract_version is distinct from 'v2'[\s\S]*identity_factual[\s\S]*\) not valid/i)
assert.match(correctiveMigration, /trace_state='TRACED'[\s\S]*li\.trace_state/i)
assert.doesNotMatch(correctiveMigration, /\bupdate\s+public\.opportunity_ingestion_events\b/i, 'historical receipts are not rewritten')
for (const field of ['ingestion_state','adapter_lineage_state','normalized_fields_snapshot','factory_status','factory_reason','factory_pipeline_version','factory_rules_version','observation_state','verification_status','lifecycle_state','source_operational_reason','universe_provenance','catalog_state','final_matching_state','alerts_state','seo_state','pipeline_health','next_action','next_action_reason','next_actions']) {
  assert(migration.includes(field), `pipeline projection includes ${field}`)
}
assert.match(sink, /opportunity_ingestion_events\?on_conflict=event_key/)
assert.match(sink, /is_source_observation": False/)
assert.match(sink, /resolve_emitted_source/)
assert.match(runner, /CVITAE_SCRAPER_RUN_DB_ID/)
assert.match(registryCore, /item\["refresh_capability"\]/)
assert.match(admin, /admin_opportunity_pipeline_ledger/)
assert.match(admin, /from\("opportunity_pipeline_status"\)/)
assert.match(adminView, /pipeline_ledger/)
assert.match(adminView, /normalized_fields_snapshot/)
assert.match(adminView, /consumer_diagnostics/)
assert.match(verifySql, /'PIPELINE_ROWS'/)
assert.match(verifySql, /'ROWS_WITHOUT_PIPELINE_STATUS'/)
assert.match(verifySql, /'UNEXPLAINED_ROWS'/)
assert.match(verifySql, /from public\.opportunity_pipeline_status/)
assert.doesNotMatch(verifySql, /\b(?:insert|update|delete|merge|call|do)\s+/i)
console.log('verify_opportunity_pipeline_contract: PASS projection=matrix ingestion_lineage=append_only verify=read_only')
