import { readFileSync } from 'node:fs'
const registry = JSON.parse(readFileSync('src/generated/source-intelligence-registry.json', 'utf8'))
const endpoint = readFileSync('netlify/functions/admin-data.ts', 'utf8')
const admin = readFileSync('src/pages/Admin.tsx', 'utf8')
if (!registry.sources?.length) throw new Error('missing generated V2 source registry')
if (!registry.registry_hash || registry.schema_version !== 'source-intelligence-registry:v2') throw new Error('registry snapshot metadata missing')
if (registry.alias_pattern_conflicts?.length) throw new Error('registry contains alias/family conflicts')
const canonicals = registry.sources.map((item: any) => item.canonical_source)
if (new Set(canonicals).size !== canonicals.length) throw new Error('aliases are rendered as duplicate canonical sources')
if (!registry.sources.some((item: any) => item.canonical_source === 'callcenters' && item.emitted_aliases.includes('cc_atento'))) throw new Error('canonical alias aggregation missing')
if (!registry.sources.some((item: any) => item.canonical_source === 'unjobs' && item.certified)) throw new Error('UNJobs certification missing from Admin artifact')
if (!endpoint.includes('source_intelligence_snapshot') || !endpoint.includes('sourceIntelligenceRegistry')) throw new Error('Admin endpoint does not consume generated core snapshot')
if (!endpoint.includes('sourceIntelligenceSnapshot') || endpoint.includes('reconcileSources')) throw new Error('Control Center retains a parallel legacy source truth')
if (!endpoint.includes('operational_health') || endpoint.includes('certified ? "HEALTHY" : "UNCERTIFIED"') || !endpoint.includes('aliasSet.has(item.source)')) throw new Error('operational health or canonical aggregation is incomplete')
if (!endpoint.includes('UNAVAILABLE_PENDING_MIGRATION')) throw new Error('restore capability is not safely unavailable before migration')
if (!endpoint.includes('source_status') || !endpoint.includes('exception_groups')) throw new Error('Admin snapshot is missing operational status or grouped exceptions')
if (!endpoint.includes('execute_automation_transition') || !endpoint.includes('apply_opportunity_automation_transition')) throw new Error('missing server-only automation bridge')
if (admin.includes('SUPABASE_SERVICE_ROLE_KEY')) throw new Error('service role key leaked to Admin client')
if (!admin.includes('sourceIntelligence') || !admin.includes('operational_health') || !admin.includes('Eight Gates') || !admin.includes('sourceIntelligenceError')) throw new Error('Admin cockpit is not consuming the operational snapshot independently')
if (endpoint.includes('apply_source_policy_suppression_atomic')) throw new Error('Admin source snapshot must not own policy apply')
console.log('verify_admin_source_intelligence: PASS')
