import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')
const workspace = read('../netlify/functions/application-workspace.ts')
const courses = read('../netlify/functions/gemini-courses.ts')
const cvVivo = read('../netlify/functions/generate-cv-vivo.ts')
const seoQueue = read('../netlify/functions/lib/seo-pipeline-runner.ts')
const indexingQueue = read('../netlify/functions/lib/indexing-queue.ts')
const maintenance = read('./refresh_opportunity_universe_maintenance.ts')
const maintenanceWorkflow = read('../.github/workflows/opportunity-universe-maintenance.yml')
const scheduledAutomation = read('./run_scheduled_source_automation.py')
const scheduledAutomationWorkflow = read('../.github/workflows/scheduled-source-automation.yml')

assert.match(workspace, /from\(['"]opportunity_catalog_universe['"]\)/, 'Application Workspace loads the canonical Catalog universe')
assert.doesNotMatch(workspace, /from\(['"]opportunities['"]\).*match_eligible|match_eligible.*from\(['"]opportunities['"]\)/s)
assert.match(courses, /from\(['"]opportunity_final_matching_universe['"]\)/, 'Gemini Courses corroborates against exact canonical Matching rows')
assert.doesNotMatch(courses, /match_eligible\s*[!=]==?\s*true/)
assert.match(cvVivo, /from\(['"]opportunity_final_matching_universe['"]\)/, 'stored CV Vivo opportunity resolves through canonical Matching')
assert.doesNotMatch(cvVivo, /from\(['"]opportunities['"]\)\s*\.insert|imported_b2c/, 'private custom vacancy never enters global opportunities')
assert.match(cvVivo, /vacancy_snapshot/, 'private vacancy remains a factual CV snapshot')
assert.match(seoQueue, /opportunity_seo_universe/, 'URL_UPDATED checks canonical effective SEO membership')
assert.match(indexingQueue, /URL_DELETED/, 'URL_DELETED remains available for prior indexed URLs')

assert.match(maintenance, /refresh_due_opportunity_universe/)
assert.match(maintenance, /refresh_dirty_opportunity_universe_sources/)
assert.match(maintenance, /maxDirtyBatches/)
assert.match(maintenanceWorkflow, /workflow_dispatch:/)
assert.doesNotMatch(maintenanceWorkflow, /schedule:|cron:/)
assert.match(maintenanceWorkflow, /confirm_prod_release_validated == 'YES'.*CVITAE_PROD_RELEASE_VALIDATED == 'true'/)
assert.match(maintenanceWorkflow, /scripts\/refresh_opportunity_universe_maintenance\.ts/)
assert.match(maintenanceWorkflow, /node-version: 24/)
assert.match(scheduledAutomation, /trigger_type.*eq\.schedule/, 'automation considers scheduled runs only')
assert.match(scheduledAutomation, /registry_auto_enabled.*is not True/, 'unknown or false durable permission is not promoted')
assert.match(scheduledAutomation, /registry_policy_hash.*expected\["registry_policy_hash"\]/, 'automation requires current registry projection')
assert.match(scheduledAutomation, /max_batches_per_run: int = 4/, 'automation is bounded and resumable')
assert.match(scheduledAutomation, /run_existing_automation\(/, 'worker reuses existing Automation Core')
assert.match(scheduledAutomationWorkflow, /workflow_dispatch:/)
assert.doesNotMatch(scheduledAutomationWorkflow, /schedule:|cron:|workflow_run:/)
assert.match(scheduledAutomationWorkflow, /confirm_prod_release_validated == 'YES'.*CVITAE_PROD_RELEASE_VALIDATED == 'true'/)
assert.match(scheduledAutomationWorkflow, /scripts\/run_scheduled_source_automation\.py/)
assert.match(scheduledAutomationWorkflow, /--max-runs 1 --batch-size 10 --max-batches-per-run 1/)
console.log('verify_b2c_secondary_contracts: PASS canonical consumers, private CV snapshot, SEO queue, bounded Universe owner and scheduled Automation Core owner')
