import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { classifyOpportunityUniverse, summarizeOpportunityUniverse, type UniversePolicy } from '../src/lib/opportunity-universe.ts'
import { canonicalPermissionSource, sourcePermissionTruth } from '../src/lib/source-permission-truth.ts'
import { hasProfessionalEvidence, professionalRequirementsText } from '../shared/professional-evidence.ts'

const now = new Date('2026-09-28T12:00:00.000Z')
const policy: UniversePolicy[] = [{ source: 'himalayas', is_enabled: true, matching_enabled: true, catalog_enabled: true, alerts_enabled: true, seo_enabled: true }]
const rich = { id: 'x', source: 'himalayas', title: 'Programme Officer', slug: 'programme-officer', organization: 'Example', description: 'A professional role with detailed responsibilities and required experience. '.repeat(2), is_active: true, verification_status: 'verified', deadline: '2026-12-31', updated_at: '2026-09-01T00:00:00.000Z', match_eligible: false }
const permission = (_source: string, _consumer: 'catalog' | 'matching' | 'alerts' | 'seo') =>
  ({ state: 'ALLOWED' as const, reason: 'FIXTURE_ALLOWED', provenance: 'fixture' })

const factualRequirement = 'Applicants must demonstrate five years of relevant programme delivery experience.'
assert.equal(professionalRequirementsText(null), '')
assert.equal(professionalRequirementsText(factualRequirement), factualRequirement)
assert.equal(professionalRequirementsText([{ text: factualRequirement, required: true }]), factualRequirement)
assert.equal(professionalRequirementsText([factualRequirement]), factualRequirement)
assert.equal(professionalRequirementsText({ summary: factualRequirement }), '', 'unsupported JSON objects contribute no evidence')
assert.equal(professionalRequirementsText([{ label: factualRequirement }]), '', 'array objects without factual text contribute no evidence')
assert.equal(hasProfessionalEvidence({ title: 'Programme Officer', description: '', requirements: [{ text: factualRequirement }] }), true, 'real JSONB requirement text crosses the existing threshold')
assert.equal(hasProfessionalEvidence({ title: 'Programme Officer', description: '', requirements: null }), false)
assert.equal(hasProfessionalEvidence({ title: 'Programme Officer', description: '', requirements: { summary: factualRequirement } }), false, 'raw JSON serialization cannot inflate professional evidence')

const hardDead = classifyOpportunityUniverse({ ...rich, is_active: false }, policy, { id: 'obs-dead', identity_status: 'DEAD', http_status: 404, observed_at: '2026-09-20T00:00:00.000Z' }, now, permission)
assert.equal(hardDead.lifecycle_state, 'HARD_DEAD', 'hard-dead observation wins over persisted active flags')
const restored = classifyOpportunityUniverse({ ...rich, is_active: false }, policy, { id: 'obs-live', identity_status: 'IDENTITY_CONFIRMED', http_status: 200, observed_at: '2026-09-20T00:00:00.000Z' }, now, permission)
assert.equal(restored.lifecycle_state, 'STALE_DERIVED_STATE')
assert.deepEqual(restored.lifecycle_repair, { is_active: true }, 'only newer positive evidence proposes restore')
const restoredAfterWrite = classifyOpportunityUniverse({ ...rich, is_active: true, updated_at: '2026-09-28T12:00:01.000Z' }, policy, { id: 'obs-live', identity_status: 'IDENTITY_CONFIRMED', http_status: 200, observed_at: '2026-09-20T00:00:00.000Z' }, now, permission, restored)
assert.equal(restoredAfterWrite.lifecycle_state, 'ACTIVE_VALID', 'RESTORE remains valid after the derived write advances updated_at')
const hardDeadAfterWrite = classifyOpportunityUniverse({ ...rich, is_active: false, updated_at: '2026-09-28T12:00:01.000Z' }, policy, { id: 'obs-dead', identity_status: 'DEAD', http_status: 404, observed_at: '2026-09-20T00:00:00.000Z' }, now, permission, hardDead)
assert.equal(hardDeadAfterWrite.lifecycle_state, 'HARD_DEAD', 'hard-dead provenance survives the derived is_active write')
const inactiveRestoredRow = { ...rich, is_active: false }
const firstApplyChanged = Boolean(restored.lifecycle_repair && inactiveRestoredRow.is_active !== restored.lifecycle_repair.is_active)
const restoredRow = { ...inactiveRestoredRow, ...restored.lifecycle_repair, updated_at: now.toISOString() }
const secondApplyDecision = classifyOpportunityUniverse(restoredRow, policy, { id: 'obs-live', identity_status: 'IDENTITY_CONFIRMED', http_status: 200, observed_at: '2026-09-20T00:00:00.000Z' }, now, permission, restored)
const secondApplyChanged = Boolean(secondApplyDecision.lifecycle_repair && restoredRow.is_active !== secondApplyDecision.lifecycle_repair.is_active)
assert.equal(firstApplyChanged, true)
assert.equal(secondApplyChanged, false, 'a repeated historical apply makes no second lifecycle mutation')
const inactiveUnknown = classifyOpportunityUniverse({ ...rich, is_active: false }, policy, null, now, permission)
assert.equal(inactiveUnknown.lifecycle_state, 'LIFECYCLE_UNKNOWN', 'persisted inactive without evidence stays unknown')
assert.equal(inactiveUnknown.seo_content_readiness_independent_of_lifecycle, 'READY', 'factual SEO potential is measured without claiming lifecycle')
assert.equal(inactiveUnknown.lifecycle_unresolved_reason, 'NO_OBSERVATION')
assert.equal(inactiveUnknown.lifecycle_recovery_class, 'REFRESH_REQUIRED')
const unknownActiveWithLiveObservation = classifyOpportunityUniverse({ ...rich, is_active: null }, policy, { id:'obs-null-live', source:'himalayas', identity_status:'IDENTITY_CONFIRMED', http_status:200, observed_at:'2026-09-20T00:00:00.000Z' }, now, permission)
assert.equal(unknownActiveWithLiveObservation.lifecycle_state, 'STALE_DERIVED_STATE', 'confirmed live evidence plus verified row resolves unknown persisted activity as repairable, not invented ACTIVE')
assert.equal(unknownActiveWithLiveObservation.lifecycle_reason, 'LATEST_LIVE_OBSERVATION_RESOLVES_UNKNOWN_ACTIVE')
assert.deepEqual(unknownActiveWithLiveObservation.lifecycle_repair, { is_active:true })
assert.equal(unknownActiveWithLiveObservation.lifecycle_recovery_class, 'RECOVERABLE_NOW')
const lifecycleThin = classifyOpportunityUniverse({ ...rich, is_active:false, description:'' }, policy, null, now, permission)
assert.equal(lifecycleThin.lifecycle_recovery_class, 'CONTENT_NOT_READY')
assert.equal(lifecycleThin.seo_content_reason, 'THIN_CONTENT')
const mismatchedObservation = classifyOpportunityUniverse({ ...rich, is_active:false }, policy, { id:'obs-other-source', source:'unjobs', identity_status:'IDENTITY_UNRESOLVED', http_status:0, observed_at:'2026-09-20T00:00:00.000Z' }, now, permission)
assert.equal(mismatchedObservation.lifecycle_unresolved_reason, 'OBSERVATION_SOURCE_MISMATCH')
assert.equal(mismatchedObservation.lifecycle_recovery_class, 'SYSTEM_ERROR')
const recoverySummary = summarizeOpportunityUniverse([inactiveUnknown, restored, lifecycleThin, mismatchedObservation])
assert.equal(recoverySummary.LIFECYCLE_UNRESOLVED_TOTAL, 4)
assert.equal(recoverySummary.LIFECYCLE_RECOVERABLE_NOW + recoverySummary.LIFECYCLE_REFRESH_REQUIRED + recoverySummary.LIFECYCLE_CONTENT_NOT_READY + recoverySummary.LIFECYCLE_SYSTEM_ERROR, recoverySummary.LIFECYCLE_UNRESOLVED_TOTAL, 'every unresolved lifecycle row is classified exactly once')
assert.equal(recoverySummary.SEO_CONTENT_READY_WHILE_LIFECYCLE_UNRESOLVED, 3)
assert.equal(recoverySummary.TOTAL_INVENTORY, recoverySummary.SEO_ROW_READY + recoverySummary.SEO_ROW_NOT_READY + recoverySummary.SEO_ROW_UNKNOWN, 'SEO row states partition the entire diagnostic inventory')
assert.equal(recoverySummary.LIFECYCLE_RECOVERY_PER_SOURCE.reduce((n, source) => n + source.lifecycle_unresolved_total, 0), recoverySummary.LIFECYCLE_UNRESOLVED_TOTAL, 'per-source unresolved accounting reconciles to global')
const expired = classifyOpportunityUniverse({ ...rich, deadline: '2020-01-01' }, policy, null, now, permission)
assert.equal(expired.lifecycle_state, 'EXPIRED')
const thin = classifyOpportunityUniverse({ ...rich, description: '', tags: ['remote', 'LATAM', 'scholarship'] }, policy, null, now, permission)
assert.equal(thin.professional_readiness, 'PROFESSIONAL_THIN', 'generic metadata tags cannot establish professional readiness')
assert.equal(thin.matching_row_state, 'NOT_READY')
const candidateEligibilityUnknown = classifyOpportunityUniverse({ ...rich, candidate_eligibility: undefined }, policy, null, now, permission)
assert.equal(candidateEligibilityUnknown.matching_row_state, 'READY', 'candidate eligibility is downstream, not a row-readiness gate')
const explicitMatchingDenied = classifyOpportunityUniverse(rich, policy, null, now, (_source, consumer) => ({ state: consumer === 'matching' ? 'DENIED' : 'ALLOWED', reason: 'explicit', provenance: 'fixture' }))
assert.equal(explicitMatchingDenied.matching_row_state, 'READY')
assert.equal(explicitMatchingDenied.final_matching_state, 'READY', 'historical source permission is advisory for first-party Matching')
const matchingSwitchOff = classifyOpportunityUniverse(rich, [{ source: 'himalayas', is_enabled: true, matching_enabled: false, consumer_switch_overrides: { matching: false } }], null, now, permission)
assert.equal(matchingSwitchOff.matching_row_state, 'READY')
assert.equal(matchingSwitchOff.source_matching_operational_state, 'DENIED')
assert.equal(matchingSwitchOff.final_matching_state, 'NOT_READY', 'operational matching disable remains effective despite permission ALLOWED')
const catalogOnlyOff = classifyOpportunityUniverse(rich, [{ ...policy[0], catalog_enabled: false, consumer_switch_overrides: { catalog: false } }], null, now, permission)
assert.equal(catalogOnlyOff.catalog_state, 'NOT_READY')
assert.equal(catalogOnlyOff.final_matching_state, 'READY', 'catalog switch affects Catalog only')
const alertsOnlyOff = classifyOpportunityUniverse(rich, [{ ...policy[0], alerts_enabled: false, consumer_switch_overrides: { alerts: false } }], null, now, permission)
assert.equal(alertsOnlyOff.alerts_state, 'NOT_READY')
assert.equal(alertsOnlyOff.final_matching_state, 'READY', 'alert switch does not alias Matching')
const seoOnlyOff = classifyOpportunityUniverse(rich, [{ ...policy[0], seo_enabled: false, consumer_switch_overrides: { seo:false } }], null, now, (_source, _consumer) => ({ state: 'ALLOWED', reason: 'FIXTURE', provenance: 'fixture' }))
assert.equal(seoOnlyOff.seo_state, 'NOT_READY', 'explicit SEO consumer switch OFF blocks this consumer only')
assert.equal(seoOnlyOff.final_matching_state, 'READY', 'SEO switch affects SEO only')
const computrabajoLegacy = { ...rich, source:'computrabajo', created_at:'2026-09-20T00:00:00Z', seo_eligible:true, seo_status:'eligible' }
const computrabajoPolicy: UniversePolicy[] = [{ source:'computrabajo', is_enabled:true, catalog_enabled:true, matching_enabled:true, alerts_enabled:true, seo_enabled:true }]
const computrabajoException = classifyOpportunityUniverse(computrabajoLegacy, computrabajoPolicy, null, new Date('2026-10-01T12:00:00Z'))
assert.equal(computrabajoException.provenance.consumer_permission_states && (computrabajoException.provenance.consumer_permission_states as any).seo,'DENIED','temporary SEO routing never rewrites permission truth')
assert.equal(computrabajoException.seo_state,'READY','qualifying legacy SEO row is READY during the window')
assert.equal(computrabajoException.seo_effective_reason,'SEO_EFFECTIVE_READY')
for (const date of ['2026-10-03T12:00:00Z','2026-10-09T23:59:59Z','2026-10-10T00:00:00Z']) {
  for (const created_at of ['2026-09-20T00:00:00Z','2026-10-05T12:00:00Z']) {
    const decision=classifyOpportunityUniverse({...computrabajoLegacy,created_at,seo_eligible:false},computrabajoPolicy,null,new Date(date))
    assert.equal(decision.seo_state,'READY')
    assert.equal(decision.provenance.temporary_legacy_seo_exception,undefined)
  }
}
assert.equal(classifyOpportunityUniverse({...computrabajoLegacy,description:'Too short'},computrabajoPolicy).seo_state,'NOT_READY')
assert.equal(classifyOpportunityUniverse(computrabajoLegacy,[{...computrabajoPolicy[0],consumer_switch_overrides:{seo:false}}]).seo_state,'NOT_READY')
const seoMissingDescription = classifyOpportunityUniverse({ ...rich, description:'' }, policy, null, now, (_source, _consumer) => ({ state: 'UNKNOWN', reason: 'NO_EVIDENCE', provenance: 'fixture' }))
assert.equal(seoMissingDescription.seo_row_state, 'NOT_READY')
assert.equal(seoMissingDescription.seo_row_reason, 'THIN_CONTENT')
assert.equal(seoMissingDescription.seo_state, 'NOT_READY')
for (const [row, reason] of [[{ ...rich, title:'' },'MISSING_TITLE'],[{ ...rich, slug:'' },'MISSING_CANONICAL_IDENTITY'],[{ ...rich, organization:'' },'MISSING_ORGANIZATION']] as const) {
  assert.equal(classifyOpportunityUniverse(row,policy,null,now,(_source,_consumer)=>({state:'UNKNOWN',reason:'NO_EVIDENCE',provenance:'fixture'})).seo_row_reason,reason)
}
const seoEnrichedUpdate = classifyOpportunityUniverse({ ...rich, source:'jobicy', description:'Factual role duties and qualifications. '.repeat(4) }, [{ ...policy[0], source:'jobicy' }], null, now, (_source, _consumer) => ({ state: 'UNKNOWN', reason: 'NO_EVIDENCE', provenance: 'fixture' }))
assert.equal(seoEnrichedUpdate.seo_row_state, 'READY', 'an update supplying the factual SEO field enters through the same reducer')
assert.equal(seoEnrichedUpdate.seo_state, 'READY', 'permission UNKNOWN remains observable but does not block first-party SEO')
assert.equal(seoEnrichedUpdate.provenance.consumer_permission_states && (seoEnrichedUpdate.provenance.consumer_permission_states as any).seo, 'UNKNOWN')
assert(seoEnrichedUpdate.source_permission_unknown_dimensions.includes('seo_index'))
const seoGloballyDisabled = classifyOpportunityUniverse(rich, [{ ...policy[0], is_enabled:false, consumer_switch_overrides:{source:false} }], null, now, (_source, _consumer) => ({ state: 'UNKNOWN', reason: 'NO_EVIDENCE', provenance: 'fixture' }))
assert.equal(seoGloballyDisabled.seo_state, 'NOT_READY')
assert.equal(seoGloballyDisabled.seo_effective_reason, 'SOURCE_DISABLED')
const seoExplicitlyRestricted = classifyOpportunityUniverse(rich, policy, null, now, (_source, consumer) => ({ state: consumer === 'seo' ? 'DENIED' : 'ALLOWED', reason: 'CONTRACT_DENY', provenance: 'fixture' }))
assert.equal(seoExplicitlyRestricted.seo_state, 'READY', 'historical source SEO evidence remains advisory under explicit product contract')
assert.equal(seoExplicitlyRestricted.seo_effective_reason, 'SEO_EFFECTIVE_READY')
assert.equal((seoExplicitlyRestricted.provenance.consumer_permission_states as any)?.seo, 'DENIED')
const unknownPermissionSwitchOn = classifyOpportunityUniverse(rich, policy, null, now, (_source, consumer) => ({ state: consumer === 'matching' ? 'UNKNOWN' : 'ALLOWED', reason: 'NO_EVIDENCE', provenance: 'fixture' }))
assert.equal(unknownPermissionSwitchOn.source_matching_state, 'UNKNOWN')
assert.equal(unknownPermissionSwitchOn.source_matching_operational_state, 'ALLOWED', 'permission UNKNOWN never rewrites an enabled operator switch')
assert.equal(unknownPermissionSwitchOn.final_matching_state, 'READY')
const unknownPolicy = classifyOpportunityUniverse({ ...rich, source: 'weworkremotely' }, [{ source: 'wwr', is_enabled: true }], null, now)
assert.equal(unknownPolicy.source_matching_state, 'DENIED', 'official WWR terms deny use to build CVitae-style job search service')
assert.equal(unknownPolicy.provenance.source, canonicalPermissionSource('wwr'), 'canonical and emitted aliases resolve to the same source identity')
assert.equal(classifyOpportunityUniverse({ ...rich, source: 'wwr' }, [{ source: 'weworkremotely', is_enabled: true }], null, now).source_matching_state, unknownPolicy.source_matching_state)
assert.equal(classifyOpportunityUniverse({ ...rich, source: 'unregistered-source' }, [], null, now).source_matching_reason, 'SOURCE_PERMISSION_NOT_EVIDENCED')
const sourceDisabled = classifyOpportunityUniverse(rich, [{ source: 'himalayas', is_enabled: false, consumer_switch_overrides:{source:false} }], null, now, permission)
assert.equal(sourceDisabled.final_matching_state, 'NOT_READY')
const himalayasReady = classifyOpportunityUniverse(rich, policy, null, now, permission)
assert.equal(himalayasReady.seo_state, 'READY', 'Himalayas public WebPage is SEO-ready when intrinsic gates pass')
assert.equal(himalayasReady.catalog_state,'READY'); assert.equal(himalayasReady.final_matching_state,'READY'); assert.equal(himalayasReady.alerts_state,'READY')
const create = classifyOpportunityUniverse({ ...rich }, policy, null, now, permission)
const update = classifyOpportunityUniverse({ ...rich, match_eligible: true }, policy, null, now, permission)
const noop = classifyOpportunityUniverse({ ...rich }, policy, null, now, permission)
assert.equal(create.final_matching_state, update.final_matching_state)
assert.deepEqual(create, noop, 'create/update/no-op use one deterministic reducer when facts are unchanged')
assert.equal(create.final_matching_state, 'READY', 'canonical final universe ignores stale persisted match_eligible')
const summary = summarizeOpportunityUniverse([hardDead, restored, inactiveUnknown, expired, thin, candidateEligibilityUnknown, explicitMatchingDenied, unknownPolicy, sourceDisabled])
assert.equal(summary.reconciliation_difference, 0, 'first-failure buckets explain every fixture row exactly once')
assert.equal(summary.FINAL_MATCHING_UNIVERSE, summary.SOURCE_MATCH_ALLOWED, 'Retrieval denominator is exactly the canonical final matching universe')
const seoSummary = summarizeOpportunityUniverse([seoEnrichedUpdate, seoMissingDescription])
assert.equal(seoSummary.SEO_ROW_READY, 1)
assert.equal(seoSummary.SEO_EFFECTIVE_READY, 1)
assert.equal(seoSummary.TOP_SEO_BLOCK_REASONS.THIN_CONTENT, 1)
const migration = readFileSync(new URL('../supabase/migrations/202609280001_opportunity_universe.sql', import.meta.url), 'utf8')
const finalCorrection = readFileSync(new URL('../supabase/migrations/202610040001_source_switch_wiring.sql', import.meta.url),'utf8')
const seoCorrection = readFileSync(new URL('../supabase/migrations/202610030002_opportunity_universe_seo_permission.sql', import.meta.url), 'utf8')
assert.match(migration,/seo_row_reason text not null[\s\S]*seo_effective_reason text not null/)
assert.match(migration,/'seo_row_reason',v_seo_row_reason[\s\S]*'seo_effective_reason',v_seo_effective_reason/)
assert.match(migration,/'seo_row_ready'[\s\S]*'seo_row_not_ready'[\s\S]*'seo_row_unknown'[\s\S]*'seo_effective_ready'[\s\S]*'top_seo_block_reasons'/)
const applyRunner = readFileSync(new URL('./apply_opportunity_universe_prod.ts', import.meta.url), 'utf8')
assert.ok(migration.includes('after insert or update on public.opportunities') && migration.includes('after insert on public.opportunity_source_observations'), 'create/update/restore and new source evidence converge on the same persisted decision trigger')
assert.ok(migration.includes('p_prior_state->\'provenance\'->>\'observation_id\'') && migration.includes('SOURCE_MATCHING_DISABLED'), 'derived lifecycle repair preserves accepted observation provenance and matching switch denial remains explicit')
assert.ok(migration.includes('reconcile_opportunity_universe_page') && migration.includes('p_apply boolean default false') && migration.includes('p_page_size > 500'), 'historical reconciliation is bounded, explicit-apply, and keyed by one canonical SQL reducer')
assert.doesNotMatch(finalCorrection,/TEMP_LEGACY_SEO_EXCEPTION|v_temp_legacy/,'final reducer retires source-specific first-party exception')
assert.match(finalCorrection,/'first_party_permission_role','ADVISORY_ONLY'/)
assert.match(seoCorrection, /insert into public\.opportunity_universe_dirty_sources[\s\S]*SOURCE_PERMISSION_ROUTING_CONTRACT_REFRESH/)
assert.doesNotMatch(seoCorrection, /reconcile_opportunity_universe_page|update\s+public\.opportunities/i, 'routing correction only queues bounded Universe policy refresh; it does not recover or mutate opportunity history')
assert.match(migration,/create or replace view public\.opportunity_seo_universe[\s\S]*where u\.seo_state='READY'/,'SEO view routes from the persisted canonical Opportunity Universe')
assert.doesNotMatch(migration,/create or replace view public\.opportunity_seo_universe[\s\S]*TEMP_LEGACY_SEO_EXCEPTION_UNTIL_2026_10_09/,'the obsolete source-specific SEO exception is not an additional routing gate')
assert.match(migration, /count\(distinct coalesce\(s\.matching_enabled::text,'UNKNOWN'\)\)/, 'NULL-versus-explicit alias policy disagreement is a conflict, not a chosen boolean')
assert.match(migration, /refresh_opportunity_universe\(p_opportunity_id text,p_apply_lifecycle_repair boolean default false\)/, 'generic decision refresh defaults to no lifecycle source mutation')
assert.match(migration, /opportunity_observation_refresh_universe[\s\S]*refresh_opportunity_universe\(new\.opportunity_id::text,true\)/, 'only new authoritative observation explicitly owns lifecycle transition')
assert.match(migration, /to_jsonb\(new\)-array\['catalog_eligible','match_eligible','alerts_eligible','seo_eligible','updated_at'\]/, 'projection-only opportunity updates are ignored by the refresh trigger')
const permissionTrigger = migration.slice(migration.indexOf('create or replace function public.opportunity_permission_refresh_universe'), migration.indexOf('create or replace function public.refresh_dirty_opportunity_universe_sources'))
assert.doesNotMatch(permissionTrigger, /refresh_opportunity_universe\(o\.id::text/, 'permission seed/update trigger never performs repeated inventory scans')
assert.match(permissionTrigger, /opportunity_universe_dirty_sources/, 'subsequent changed permission queues a coalesced source refresh')
const sourcePolicyTrigger = migration.slice(migration.indexOf('create or replace function public.opportunity_source_policy_refresh_universe'), migration.indexOf('create or replace function public.opportunity_permission_refresh_universe'))
assert.match(sourcePolicyTrigger, /opportunity_universe_dirty_sources/, 'source policy changes queue one canonical coalesced refresh')
assert.match(sourcePolicyTrigger, /update of source,is_enabled,catalog_enabled,matching_enabled,alerts_enabled,seo_enabled/, 'all consumer switch transitions invalidate persisted universe state')
assert.doesNotMatch(sourcePolicyTrigger, /refresh_opportunity_universe\(o\.id::text,true\)|update public\.opportunities set is_active/i, 'source policy changes cannot apply historical lifecycle repair')
const pageReducer = migration.slice(migration.indexOf('create or replace function public.reconcile_opportunity_universe_page'), migration.indexOf('create or replace function public.get_opportunity_universe_summary'))
assert.match(pageReducer, /refresh_opportunity_universe\(v_row\.row_id,true\)/, 'explicit historical apply is the one lifecycle repair owner')
assert.doesNotMatch(pageReducer, /update public\.opportunities set is_active/i, 'page reconciler does not duplicate lifecycle mutation')
assert.match(pageReducer, /lifecycle_flag_changed/, 'changed lifecycle count reflects the actual update result')
assert.match(applyRunner, /pageSize = Number\(args\.get\('--page-size'\) \?\? 250\)/)
assert.match(applyRunner, /writeFileSync\(stateFile/, 'bounded apply runner persists its cursor only after a successful page call')
assert.match(applyRunner, /REQUIRES_EXPLICIT --apply --confirm YES/)
const summarySql = migration.slice(migration.indexOf('create or replace function public.get_opportunity_universe_summary'), migration.indexOf('create or replace function public.get_opportunity_universe_row'))
for (const key of ['inventory_state_reconciliation_difference','matching_first_failure_reconciliation_difference','active_matching_reconciliation_difference']) assert.equal((summarySql.match(new RegExp(`'${key}'`, 'g')) || []).length, 1, `summary has one distinct ${key}`)
assert.equal((summarySql.match(/'matching_reconciliation_difference'/g) || []).length, 0, 'ambiguous duplicate summary key removed')
assert.ok(summarySql.includes('routing_unresolved_rows') && summarySql.includes('rows_with_any_source_permission_unknown') && summarySql.includes('source_permission_unknown_dimension_claims'), 'routing unresolved and 10-dimension permission unknowns stay separate')

const permissionCoverageFixture = classifyOpportunityUniverse({ ...rich, source: 'himalayas' }, policy, null, now)
const permissionCoverageSummary = summarizeOpportunityUniverse([permissionCoverageFixture])
assert.equal(permissionCoverageSummary.ROUTING_UNRESOLVED_ROWS, 0, 'unknown application/distribution permission does not make current matching routing unresolved')
assert.equal(permissionCoverageSummary.ROWS_WITH_ANY_SOURCE_PERMISSION_UNKNOWN, 0, 'Himalayas now has explicit permission evidence for all ten dimensions')
const aliasConflict = classifyOpportunityUniverse(rich, [{ source: 'himalayas', is_enabled: true, matching_enabled: true }, { source: 'himalayas', is_enabled: false, matching_enabled: true, consumer_switch_overrides:{source:false} }], null, now, permission)
assert.equal(aliasConflict.source_operational_state, 'CONFLICT')
assert.equal(summarizeOpportunityUniverse([aliasConflict]).first_failure.SOURCE_POLICY_ALIAS_CONFLICT, 1)
const allowAllConsumers = (_source: string, _consumer: string) => ({ state: 'ALLOWED' as const, reason: 'fixture', provenance: 'fixture' })
const allSwitchesOn: UniversePolicy = { source: 'himalayas', is_enabled: true, matching_enabled: true, catalog_enabled: true, alerts_enabled: true, seo_enabled: true }
const seoAliasConflict = classifyOpportunityUniverse(rich, [{ ...allSwitchesOn }, { ...allSwitchesOn, source: 'HIMALAYAS', seo_enabled: false, consumer_switch_overrides: { seo:false } }], null, now, allowAllConsumers)
assert.equal(seoAliasConflict.final_matching_state, 'READY', 'SEO alias conflict does not alter Matching')
assert.equal(seoAliasConflict.catalog_state, 'READY', 'SEO alias conflict does not alter Catalog')
assert.equal(seoAliasConflict.alerts_state, 'READY', 'SEO alias conflict does not alter Alerts')
assert.equal(seoAliasConflict.seo_operational_state, 'UNKNOWN', 'SEO-only alias conflict affects only SEO switch truth')
const matchingAliasConflict = classifyOpportunityUniverse(rich, [{ ...allSwitchesOn }, { ...allSwitchesOn, source: 'HIMALAYAS', matching_enabled: false, consumer_switch_overrides: { matching: false } }], null, now, allowAllConsumers)
assert.equal(matchingAliasConflict.final_matching_state, 'UNKNOWN')
assert.equal(matchingAliasConflict.catalog_state, 'READY')
assert.equal(matchingAliasConflict.alerts_state, 'READY')
assert.equal(matchingAliasConflict.seo_state, 'READY')
for (const [field, consumer] of [['catalog_enabled', 'catalog'], ['alerts_enabled', 'alerts']] as const) {
  const conflicted = classifyOpportunityUniverse(rich, [{ ...allSwitchesOn }, { ...allSwitchesOn, source: 'HIMALAYAS', [field]: false, consumer_switch_overrides: { [consumer]: false } }], null, now, allowAllConsumers)
  assert.equal((conflicted as any)[`${consumer}_operational_state`], 'UNKNOWN')
  for (const other of (['catalog', 'matching', 'alerts', 'seo'] as const).filter(value => value !== consumer)) {
    assert.equal(other === 'matching' ? conflicted.final_matching_state : (conflicted as any)[`${other}_state`], 'READY', `${field} conflict is dimension-local`)
  }
}
const globalAliasConflict = classifyOpportunityUniverse(rich, [{ ...allSwitchesOn }, { ...allSwitchesOn, source: 'HIMALAYAS', is_enabled: false, consumer_switch_overrides:{source:false} }], null, now, allowAllConsumers)
assert.equal(globalAliasConflict.source_operational_state, 'CONFLICT')
assert.equal(globalAliasConflict.catalog_state, 'UNKNOWN')
assert.equal(globalAliasConflict.final_matching_state, 'UNKNOWN')
assert.equal(globalAliasConflict.alerts_state, 'UNKNOWN')
assert.equal(globalAliasConflict.seo_state, 'UNKNOWN')
const matchingDeniedAlertsAllowed = classifyOpportunityUniverse(rich, [{ ...allSwitchesOn, matching_enabled: false, consumer_switch_overrides:{matching:false} }], null, now, (_source, consumer) => ({ state: consumer === 'matching' ? 'DENIED' as const : 'ALLOWED' as const, reason: 'fixture', provenance: 'fixture' }))
assert.equal(matchingDeniedAlertsAllowed.final_matching_state, 'NOT_READY')
assert.equal(matchingDeniedAlertsAllowed.alerts_state, 'READY', 'Alerts are independently ready when Matching permission/switch are denied')
const alertsDeniedMatchingAllowed = classifyOpportunityUniverse(rich, [{ ...allSwitchesOn, alerts_enabled: false, consumer_switch_overrides:{alerts:false} }], null, now, (_source, consumer) => ({ state: consumer === 'alerts' ? 'DENIED' as const : 'ALLOWED' as const, reason: 'fixture', provenance: 'fixture' }))
assert.equal(alertsDeniedMatchingAllowed.final_matching_state, 'READY')
assert.equal(alertsDeniedMatchingAllowed.alerts_state, 'NOT_READY', 'Matching readiness does not override Alerts permission/switch')
const matchBatchSource = readFileSync(new URL('../supabase/functions/match-batch/index.ts', import.meta.url), 'utf8')
const alertSenderSource = readFileSync(new URL('../netlify/functions/send-high-match-alerts.ts', import.meta.url), 'utf8')
assert.match(matchBatchSource, /from\(requestMode === 'alerts' \? 'opportunity_alert_universe' : 'opportunity_final_matching_universe'\)/, 'alerts recent and background hydration use Alert Universe authority')
assert.match(matchBatchSource, /requestMode === 'alerts' \|\| sourceMatchingAllowed/, 'only default Matching path applies Matching operational source policy')
assert.match(alertSenderSource, /from\("opportunity_alert_universe"\)[\s\S]*?\.lte\('updated_at', progress.cutoff\)[\s\S]*?\.limit\(pageSize\)/, 'bounded durable Alert cursor reads the canonical Alert Universe')
assert.doesNotMatch(alertSenderSource, /from\("opportunity_final_matching_universe"\)/, 'Alert candidate denominator never uses Matching Universe')
const unknownAliasConflict = classifyOpportunityUniverse(rich, [{ source: 'himalayas', is_enabled: true, matching_enabled: true }, { source: 'himalayas', is_enabled: true }], null, now, permission)
assert.equal(unknownAliasConflict.source_operational_state, 'ENABLED', 'matching-only missing alias state does not conflict the global source switch')
assert.equal(unknownAliasConflict.source_matching_operational_state, 'ALLOWED', 'missing/default Matching alias synchronizes only under explicit ALLOWED permission and enabled source')
const canonicalUnknown = classifyOpportunityUniverse({ ...rich, source: 'talentcom' }, [{ source: 'talentcom', is_enabled: true, matching_enabled: false }], null, now)
assert.equal(canonicalUnknown.source_matching_state, 'UNKNOWN')
assert.equal(canonicalUnknown.source_matching_operational_state, 'ALLOWED', 'operational default is independent of UNKNOWN advisory permission; row gates decide final consumer')
assert.equal(canonicalUnknown.final_matching_state, 'READY')

assert.equal(canonicalPermissionSource('wwr'), canonicalPermissionSource('weworkremotely'))
assert.equal(sourcePermissionTruth('jobicy','catalog').state, 'ALLOWED')
assert.equal(sourcePermissionTruth('jobicy','matching').state, 'ALLOWED')
assert.equal(sourcePermissionTruth('jobicy','alerts').state, 'ALLOWED')
assert.equal(sourcePermissionTruth('jobicy','seo').state, 'UNKNOWN')
assert.equal(sourcePermissionTruth('jobicy','matching').evidence_type, 'OFFICIAL_API_DOCUMENTATION')

const prod28SepBaseline = { total: 16405, inactive_or_unknown: 9272, deadline_expired: 91, source_matching_disabled: 6460, match_eligibility_unexplained: 429, source_allowed: 153 }
assert.equal(Object.values(prod28SepBaseline).slice(1).reduce((sum, value) => sum + value, 0), prod28SepBaseline.total, 'historical baseline first-failure categories reconcile exactly')
console.log('verify_opportunity_universe: PASS lifecycle-hard-dead/stale/unknown/expired, row-vs-source, permission-separation, parity, first-failure reconciliation, 2026-09-28 baseline')
