import fs from 'node:fs'
import assert from 'node:assert/strict'
import { canonicalCandidateEligibility, confirmedCandidateEligibility, evaluateOpportunityEligibility } from '../shared/candidate-eligibility.ts'

const read = (file: string) => fs.readFileSync(file, 'utf8')
const dashboard = read('src/hub/Dashboard.tsx')
const profileBuilder = read('src/hub/ProfileBuilder.tsx')
const coverageCard = read('src/components/cv/MatchingCoverageCard.tsx')
const cvVivo = read('src/hub/CVVivo.tsx')
const analyzer = read('src/components/CVAnalyzer.tsx')
const loader = read('src/components/cv/B2CProgressLoader.tsx')
const css = read('src/index.css')
const learning = read('src/hub/LearningPlan.tsx')
const rewrite = read('src/hub/CVRewrite.tsx')
const ats = read('src/hub/ATSDiagnostic.tsx')
const guide = read('src/components/cv/ProductGuide.tsx')
const reporter = read('src/components/cv/FeedbackReporter.tsx')
const matching = read('supabase/functions/match-batch/index.ts')
const courses = read('netlify/functions/gemini-courses.ts')

assert.match(matching, /\.limit\(300\)/, 'La ventana primaria de matching debe seguir siendo explícita')
assert.match(matching, /match_count:\s*120/, 'La ventana semántica debe seguir siendo explícita')
assert.doesNotMatch(dashboard, /(?<![A-Za-z-])300(?![A-Za-z-])|(?<![A-Za-z-])1154(?![A-Za-z-])|vacantes activas/, 'Dashboard no debe presentar caps o inventario como total')
assert.doesNotMatch(analyzer, /\b1154\b|vacantes activas/, 'CVAnalyzer no debe presentar un inventario congelado como total')
assert.match(dashboard, /Buscando oportunidades elegibles/)
assert.match(dashboard, /Todavía no encontramos coincidencias suficientemente respaldadas/)
assert.match(dashboard, /Esto no significa que no haya oportunidades/)
assert.match(dashboard, /const nextMatches = \(data\.matches \|\| \[\]\)\.filter/, 'Dashboard must retain all server-confirmed matches before the presentation gate')
assert.match(dashboard, /matches\.slice\(1, isSubscribed \? undefined : 3\)/, 'Free top-three is a presentation-only gate')
assert.match(dashboard, /matches\.length - 3/, 'Free users receive an aggregate count of additional matches')
assert.match(dashboard, /coverage_state === 'ELIGIBILITY_UNKNOWN'[\s\S]*Confirmar mi elegibilidad/, 'zero-match eligibility-unknown state prioritizes the profile CTA')
assert.match(coverageCard, /state === 'ELIGIBILITY_UNKNOWN'[\s\S]*href="\/mi-carrera\/perfil"/, 'coverage card provides direct eligibility action')
assert.match(coverageCard, /otras pueden seguir sin elegibilidad confirmada/, 'residence confirmation is not promised to resolve every unknown')
assert.match(profileBuilder, /Confirmar tu país de residencia ayuda a evaluar oportunidades/)
assert.match(profileBuilder, /CVitae no lo deduce de tu ubicación escrita ni de tu CV/)
assert.match(profileBuilder, /Recomendado para obtener matches confirmados/)
assert.doesNotMatch(profileBuilder, /candidate_eligibility\s*:\s*[^,\n]*location/, 'free-text location never populates candidate eligibility')
assert.equal(canonicalCandidateEligibility(undefined).residence_country, '', 'unconfirmed residence remains empty')
assert.equal(evaluateOpportunityEligibility(canonicalCandidateEligibility(undefined), { remote: true, eligible_countries: ['PY'] }).state, 'UNKNOWN', 'empty eligibility does not become Paraguay')
assert.equal(evaluateOpportunityEligibility(confirmedCandidateEligibility({ residence_country: 'PY' }), { remote: true, eligible_countries: ['PY'] }).state, 'ELIGIBLE')
assert.equal(evaluateOpportunityEligibility(confirmedCandidateEligibility({ residence_country: 'PY' }), { remote: true, eligible_countries: ['US'] }).state, 'INELIGIBLE', 'US-only mismatch remains a hard geographic denial')
assert.match(cvVivo, /daily_usage:[\s\S]{0,180}cv_vivo: currentCount \+ 1/, 'Free CV Vivo usage telemetry remains available for future entitlement policy')
assert.match(cvVivo, /Durante esta beta, el uso no tiene límite diario/, 'beta CV Vivo is not hard-gated at one generation per day')
assert.doesNotMatch(cvVivo, /if\s*\([^)]*cvVivoUsedToday[^)]*\)\s*(?:\{[^}]*return|return)/, 'daily telemetry cannot block CV Vivo generation')
assert.doesNotMatch(dashboard, /Completá tu perfil con más habilidades para ver oportunidades/)

assert.match(loader, /role="status"/)
assert.match(loader, /aria-live="polite"/)
assert.match(loader, /activeIndex !== undefined/, 'Dashboard must retain explicit real-stage control')
assert.match(loader, /setInterval/, 'Long operations need a bounded communication fallback when no real step exists')
assert.match(loader, /clearInterval/, 'Loader auto-cycle must clean up on unmount')
assert.match(loader, /prefers-reduced-motion/, 'Loader auto-cycle must respect reduced motion')
assert.match(css, /transform-style:\s*preserve-3d/)
assert.match(css, /prefers-reduced-motion: reduce/)
assert.doesNotMatch(loader, /w-\[(?:340|360)px\]/)

assert.match(learning, /Tu plan para acercarte a tu objetivo/)
assert.match(learning, /oportunidades reales/)
assert.match(learning, /brechas respaldadas/)
assert.match(learning, /No se guardan como skills del CV/)
assert.match(courses, /officialProvider|providerAllowlist|ALLOWED|microsoft_learn/)

assert.match(rewrite, /Elegí qué CV querés mejorar/)
assert.match(rewrite, /Más claro para ATS/)
assert.match(rewrite, /sin inventar resultados/)
assert.match(rewrite, /Cambiamos cómo lo contás, no los hechos/)
assert.match(rewrite, /text-3xl[^\"]*sm:text-4xl/)
assert.match(ats, /No existe un único ATS universal/)
assert.match(ats, /Usar un CV guardado/)
assert.match(ats, /Subir otro CV/)
assert.match(ats, /text-3xl[^\"]*sm:text-4xl/)

assert.match(guide, /max-width:|w-\[min\(320px/)
assert.match(guide, /max-\[430px\]:sr-only/)
assert.match(reporter, /max-\[430px\]:sr-only/)
assert.match(reporter, /No adjuntamos automáticamente tu CV/)

// Shared B2B contracts: only stable safety markers are asserted; no B2B code is modified here.
const createVacancy = read('netlify/functions/create-vacancy.ts')
const analyzeApplicants = read('netlify/functions/analyze-vacancy-applicants.ts')
const compareCandidates = read('netlify/functions/compare-candidates.ts')
const analyzeCandidate = read('netlify/functions/analyze-cv-candidate.ts')
assert.match(createVacancy, /create_recruiter_vacancy_atomic/)
assert.match(createVacancy, /opportunity_id/)
assert.match(analyzeApplicants, /progress|cursor|offset|limit/i)
assert.match(compareCandidates, /ownership|recruiter|company|organization/i)
assert.match(analyzeCandidate, /recruiter|b2b|mode/i)

console.log('ITEM57_VALUE_CLARITY_OK=1')
console.log('matching_caps_internal=1')
console.log('truthful_zero_match=1')
console.log('shared_loader_accessible=1')
console.log('mobile_controls_compact=1')
console.log('b2b_contract_markers=1')
