import fs from 'node:fs'
import assert from 'node:assert/strict'
import { applicationReturnTo, isSafeApplicationReturnTo } from '../src/lib/application-intent.ts'

const read = (file: string) => fs.readFileSync(file, 'utf8')
const job = read('src/pages/JobDetail.tsx')
const opportunity = read('src/pages/OpportunityDetail.tsx')
const workspace = read('src/hub/ApplicationWorkspace.tsx')
const auth = read('src/pages/AuthCallback.tsx')
const profile = read('src/hub/ProfileBuilder.tsx')
const backend = read('netlify/functions/application-workspace.ts')
const presentation = read('src/components/cvitae/OpportunityPresentation.tsx')
const fixture = JSON.parse(fs.readFileSync('scripts/fixtures/seo-inventory.json', 'utf8'))

assert.equal(applicationReturnTo('bogota-4f416c75'), '/mi-carrera/postular/bogota-4f416c75')
assert.equal(isSafeApplicationReturnTo(applicationReturnTo('bogota-4f416c75')), true)
assert.equal(isSafeApplicationReturnTo('https://evil.example'), false)
assert.equal(isSafeApplicationReturnTo('/mi-carrera/postular/a?next=evil'), false)

for (const page of [job, opportunity]) {
  assert.match(page, /canonicalOpportunityUrlForRow/)
  assert.match(page, /aggregatedJobPosting/)
  assert.match(page, /OpportunityApplicationCta/)
  assert.match(page, /StructuredOpportunityDescription/)
  assert.match(page, /CvitaeOpportunityValue/)
  assert.match(page, /text-3xl[^"]*sm:text-5xl/)
}
assert.match(presentation, /Ver descripción original completa/)
assert.match(presentation, /aria-expanded=\{open\}/)
assert.match(presentation, /aria-controls=\{contentId\}/)
assert.match(presentation, /Ocultar descripción original/)
assert.match(presentation, /formatOpportunityValue/)
assert.match(presentation, /Esta oportunidad en 30 segundos/)
assert.match(presentation, /full_time: 'Tiempo completo'/)
assert.match(presentation, /toLocaleDateString\('es-PY'/)
assert.doesNotMatch(presentation, /source ===|unjobs|Bogotá|Bogota/)
assert.ok(new Set(fixture.opportunities.filter((row: any) => row.source).map((row: any) => row.source)).size >= 2, 'fixture must cover multiple sources')
assert.ok(fixture.opportunities.some((row: any) => row.opportunity_type !== 'job'), 'fixture must cover a non-job type')
assert.match(presentation, /SIN INVENTAR EXPERIENCIA/)
assert.match(presentation, /EVIDENCIA CONFIRMADA/)
assert.match(workspace, /opportunitySlug: slug/)
assert.match(workspace, /returnTo/)
assert.match(auth, /consumeApplicationReturnTo/)
assert.match(profile, /consumeApplicationReturnTo/)
assert.match(backend, /confirmedEvidence/)
assert.match(backend, /requirement_analysis/)
assert.match(backend, /opportunitySnapshot/)
assert.doesNotMatch(presentation, /Empresa no informada|Ubicaci.n no informada|Paraguay/)

console.log('ITEM56_B2C_OK=1')
console.log('exact_opportunity_identity=1')
console.log('auth_intent_preserved=1')
console.log('requirements_evidence_separate=1')
console.log('shared_public_renderer=1')
console.log('no_factual_fallbacks=1')
console.log('accordion_accessible=1')
console.log('source_agnostic_renderer=1')
console.log('presentation_formatting=1')
