import assert from 'node:assert/strict'
import { canonicalSource, evaluateOpportunityDistribution, type SourcePolicyRow } from '../src/lib/effective-source-policy.ts'
import { publicOpportunitySchemaType } from '../src/lib/opportunity-truth.ts'
import { aggregatedJobPosting } from '../src/lib/factual-job-posting.ts'
import { sourcePermissionDimensionTruth } from '../src/lib/source-permission-truth.ts'

const rich = { source:'computrabajo', slug:'programme-officer', title:'Programme Officer', organization:'Acme', description:'Coordinate programmes, monitor results, prepare reports and collaborate with partners. '.repeat(2), tags:['programme management','monitoring'], opportunity_type:'job', is_active:true, verification_status:'verified', created_at:'2026-09-20T00:00:00Z', catalog_eligible:true, match_eligible:true, alerts_eligible:true, seo_eligible:true, seo_status:'eligible' }
const policy = (source:string, extra:Partial<SourcePolicyRow> = {}):SourcePolicyRow => ({ source, is_enabled:true, catalog_enabled:true, matching_enabled:true, alerts_enabled:true, seo_enabled:true, web_catalog_allowed:true, search_engine_indexing_allowed:true, google_jobs_distribution_allowed:true, ...extra })
let result = evaluateOpportunityDistribution(rich, [policy('computrabajo', { web_catalog_allowed:false, search_engine_indexing_allowed:null, google_jobs_distribution_allowed:false })])
assert.equal(result.catalog.allowed, false, 'explicit Computrabajo reproduction restriction denies catalog use')
assert.equal(result.catalog.capabilityState, 'DENIED')
assert(result.catalog.reasons.includes('SOURCE_CATALOG_PERMISSION_DENIED'))
assert.equal(result.seo.allowed, true, 'legacy SEO exception is specific to Computrabajo and does not change permission truth')
assert.equal(result.seo.capabilityState, 'DENIED')
assert.equal(result.seo.temporaryException?.applied, true)
assert.equal(result.googleJobs.allowed, false)
assert.equal(result.catalog.adminSwitchState, 'ENABLED')
result = evaluateOpportunityDistribution({...rich, source:'oyaop', title:'Open Opportunity', description:'', tags:[]}, [policy('oya', { is_enabled:false, matching_enabled:false, web_catalog_allowed:false })])
assert.equal(canonicalSource('oyaop'), 'oya'); assert.equal(result.canonicalSource, 'oya'); assert.equal(result.matching.allowed, false); assert(result.matching.reasons.includes('INSUFFICIENT_PROFESSIONAL_EVIDENCE'))
result = evaluateOpportunityDistribution(rich, [policy('himalayas', { catalog_enabled:false, matching_enabled:false, alerts_enabled:false, seo_enabled:false, web_catalog_allowed:true, search_engine_indexing_allowed:false, google_jobs_distribution_allowed:false })])
assert.equal(result.policyFound, false, 'unresolved source does not inherit Himalayas policy')
result = evaluateOpportunityDistribution({...rich, source:'himalayas'}, [policy('himalayas', { catalog_enabled:false, matching_enabled:false, alerts_enabled:false, seo_enabled:false, web_catalog_allowed:true, search_engine_indexing_allowed:false, google_jobs_distribution_allowed:false })])
assert.equal(result.catalog.allowed, false); assert(result.catalog.reasons.includes('SOURCE_CATALOG_OPERATOR_DISABLED'))
assert.equal(result.matching.allowed, false); assert.equal(result.matching.reasons.includes('SOURCE_MATCHING_OPERATOR_DISABLED'), true)
assert.equal(result.alerts.allowed, false); assert(result.alerts.reasons.includes('SOURCE_ALERTS_OPERATOR_DISABLED'))
assert.equal(result.seo.allowed, true, 'first-party SEO uses intrinsic readiness without a source-by-source SEO switch')
assert.equal(result.googleJobs.allowed, false)
for (const [consumer, field] of [['catalog','catalog_enabled'],['matching','matching_enabled'],['alerts','alerts_enabled']] as const) {
  const switchOff = evaluateOpportunityDistribution({ ...rich, source:'himalayas' }, [policy('himalayas', { [field]:false })])
  assert.equal(switchOff[consumer].capabilityState, 'ALLOWED', `${consumer} permission remains ALLOWED while its switch is OFF`)
  assert.equal(switchOff[consumer].allowed, false)
  assert(switchOff[consumer].reasons.includes(`SOURCE_${consumer.toUpperCase()}_OPERATOR_DISABLED`), `${consumer} is causally blocked by operator switch`)
}
const legacyBeforeExpiry = evaluateOpportunityDistribution(rich, [policy('computrabajo')], new Date('2026-10-01T12:00:00Z'))
assert.equal(sourcePermissionDimensionTruth('computrabajo','seo_index').state,'DENIED','temporary exception never alters canonical permission truth')
assert.equal(legacyBeforeExpiry.seo.capabilityState,'DENIED')
assert.equal(legacyBeforeExpiry.seo.allowed,true,'first-party SEO is allowed from global source state and intrinsic readiness, independently of permission truth')
assert.equal(legacyBeforeExpiry.seo.temporaryException?.name,'TEMP_LEGACY_SEO_EXCEPTION_UNTIL_2026_10_09')
assert.equal(legacyBeforeExpiry.seo.temporaryException?.state,'ACTIVE')
assert.equal(legacyBeforeExpiry.seo.temporaryException?.expiresOn,'2026-10-09')
assert.equal(legacyBeforeExpiry.seo.temporaryException?.applied,true)
assert.equal(legacyBeforeExpiry.seo.permissionReasons.includes('SOURCE_SEO_PERMISSION_DENIED'),true)
assert.equal(legacyBeforeExpiry.catalog.allowed,false)
assert.equal(legacyBeforeExpiry.matching.allowed,false)
assert.equal(legacyBeforeExpiry.alerts.allowed,false)
assert.equal(legacyBeforeExpiry.jobPosting.allowed,false)
assert.equal(legacyBeforeExpiry.googleJobs.allowed,false)
assert.equal(legacyBeforeExpiry.thirdParty.allowed,false)
const legacyOnExpiryDate = evaluateOpportunityDistribution(rich, [policy('computrabajo')], new Date('2026-10-09T23:59:59Z'))
assert.equal(legacyOnExpiryDate.seo.allowed,true,'the explicitly inclusive final observation date remains active')
const legacyExpired = evaluateOpportunityDistribution(rich, [policy('computrabajo')], new Date('2026-10-10T00:00:00Z'))
assert.equal(legacyExpired.seo.allowed,true,'the expired legacy exception does not disable the general first-party SEO contract')
assert.equal(legacyExpired.seo.temporaryException?.state,'EXPIRED')
assert.equal(legacyExpired.seo.temporaryException?.applied,false)
const noLongerLegacy = evaluateOpportunityDistribution({ ...rich, seo_eligible:false }, [policy('computrabajo')], new Date('2026-10-01T12:00:00Z'))
assert.equal(noLongerLegacy.seo.allowed,true,'intrinsic readiness, not the legacy seo_eligible projection, determines first-party routing')
assert.equal(noLongerLegacy.seo.temporaryException?.applied,false)
const newRowDuringWindow = evaluateOpportunityDistribution({ ...rich, created_at:'2026-10-05T12:00:00Z' }, [policy('computrabajo')], new Date('2026-10-05T12:00:00Z'))
assert.equal(newRowDuringWindow.seo.allowed,true,'new qualifying Computrabajo rows enter first-party SEO during the live observation window')
assert.equal(newRowDuringWindow.seo.temporaryException?.applied,true)
assert.equal(newRowDuringWindow.seo.capabilityState,'DENIED','the live window does not change canonical permission truth')
const sameNewRowAfterWindow = evaluateOpportunityDistribution({ ...rich, created_at:'2026-10-05T12:00:00Z' }, [policy('computrabajo')], new Date('2026-10-10T00:00:00Z'))
assert.equal(sameNewRowAfterWindow.seo.allowed,true,'first-party SEO is not bounded by the obsolete source-permission exception window')
assert.equal(sameNewRowAfterWindow.seo.temporaryException?.state,'EXPIRED')
const thinDuringWindow = evaluateOpportunityDistribution({ ...rich, created_at:'2026-10-05T12:00:00Z', description:'Too short' }, [policy('computrabajo')], new Date('2026-10-05T12:00:00Z'))
assert.equal(thinDuringWindow.seo.allowed,false,'the exception does not bypass normal SEO quality gates')
assert.equal(thinDuringWindow.seo.temporaryException?.applied,false)
const ctSwitchOff = evaluateOpportunityDistribution(rich, [policy('computrabajo', { seo_enabled:false })], new Date('2026-10-01T12:00:00Z'))
assert.equal(ctSwitchOff.seo.allowed,true,'first-party SEO exception is independent of the legacy SEO switch')
assert.equal(ctSwitchOff.seo.reasons.includes('SOURCE_SEO_OPERATOR_DISABLED'),false)
result = evaluateOpportunityDistribution(rich, [policy('computrabajo')], new Date('2026-10-10T00:00:00Z'))
assert.equal(result.catalog.allowed, false); assert.equal(result.matching.allowed, false); assert.equal(result.alerts.allowed, false); assert.equal(result.seo.allowed, true); assert.equal(result.jobPosting.allowed, false); assert.equal(result.googleJobs.allowed, false); assert.equal(result.thirdParty.allowed, false)
assert.equal(sourcePermissionDimensionTruth('computrabajo', 'collect').state, 'DENIED')
assert.equal(sourcePermissionDimensionTruth('computrabajo', 'detail_fetch').state, 'DENIED')
assert.equal(sourcePermissionDimensionTruth('computrabajo', 'catalog').state, 'DENIED')
assert.equal(sourcePermissionDimensionTruth('computrabajo', 'alerts').state, 'DENIED')
assert.equal(sourcePermissionDimensionTruth('computrabajo', 'seo_index').state, 'DENIED')
assert.equal(sourcePermissionDimensionTruth('computrabajo', 'google_jobs').state, 'DENIED')
assert.equal(sourcePermissionDimensionTruth('computrabajo', 'third_party_distribution').state, 'DENIED')
assert.equal(sourcePermissionDimensionTruth('computrabajo', 'matching').state, 'UNKNOWN')
assert.equal(sourcePermissionDimensionTruth('computrabajo', 'application_routing').state, 'UNKNOWN')
assert.equal(sourcePermissionDimensionTruth('computrabajo', 'attribution_requirement').state, 'UNKNOWN')

const himalayasRow = { ...rich, source:'himalayas', slug:'himalayas-organic-role', country_code:'PY', city:'Asunción', published_at:'2026-09-01T00:00:00Z' }
const himalayasPolicy = policy('himalayas')
const himalayas = evaluateOpportunityDistribution(himalayasRow, [himalayasPolicy])
assert.equal(himalayas.seo.capabilityState, 'ALLOWED')
assert.equal(himalayas.seo.allowed, true, 'Himalayas first-party organic SEO is permitted with SEO switch enabled')
assert.equal(himalayas.catalog.allowed, true)
assert.equal(himalayas.matching.allowed, true)
assert.equal(himalayas.alerts.allowed, true)
assert.equal(himalayas.jobPosting.allowed, false, 'JobPosting follows Google Jobs permission, not SEO_INDEX')
assert.equal(himalayas.googleJobs.allowed, false)
assert.equal(himalayas.thirdParty.allowed, false)
const structured = aggregatedJobPosting({ ...himalayasRow, distribution:himalayas }, 'https://cvitae.lat/empleos/himalayas-organic-role')
assert.equal(structured.state, 'NOT_READY')
assert(structured.reasons.includes('JOBPOSTING_NOT_ALLOWED'))
assert.equal(publicOpportunitySchemaType(himalayasRow, structured.state === 'READY'), 'WebPage', 'public factual page retains generic schema and does not emit JobPosting')
const seoSwitchOff = evaluateOpportunityDistribution(himalayasRow, [policy('himalayas', { seo_enabled:false })])
assert.equal(seoSwitchOff.seo.capabilityState, 'ALLOWED', 'permission remains allowed when the operator disables the switch')
assert.equal(seoSwitchOff.seo.allowed, true, 'legacy seo_enabled is diagnostic and does not block ready first-party pages')
assert(!seoSwitchOff.seo.reasons.includes('SOURCE_SEO_OPERATOR_DISABLED'))
assert(!seoSwitchOff.seo.reasons.includes('SOURCE_SEO_PERMISSION_DENIED'))
const unknownSeoPermissionReady = evaluateOpportunityDistribution({ ...himalayasRow, source:'jobicy' }, [policy('jobicy', { seo_enabled:false })])
assert.equal(unknownSeoPermissionReady.seo.capabilityState, 'UNKNOWN', 'permission evidence remains UNKNOWN')
assert.equal(unknownSeoPermissionReady.seo.allowed, true, 'UNKNOWN alone does not destroy intrinsic first-party SEO readiness')
assert.equal(unknownSeoPermissionReady.seo.adminSwitchState,'LEGACY_CONFIG_DISABLED')
assert(unknownSeoPermissionReady.seo.permissionReasons.includes('SOURCE_SEO_PERMISSION_UNKNOWN'))
assert.equal(unknownSeoPermissionReady.googleJobs.allowed, false, 'external Google Jobs remains fail-closed on unknown permission')
console.log('verify_effective_source_policy: PASS')
